# Default values for farsight-collector-colo.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

########################################
### MUST CONFIGURE TO BE ABLE TO RUN ###
########################################
aws:
  s3Url: ""
  sqsUrl: ""
  defaultRegion: ""


###########################
### CONFIGURE IF NEEDED ###
###########################
nmsg:
  sources:
    - 10.32.202.255/8430
    - 10.32.202.255/8431
    - 10.32.202.255/8432
    - 10.32.202.255/8433
    - 10.32.202.255/8434
    - 10.32.202.255/8435
    - 10.32.202.255/8436
    - 10.32.202.255/8437

compressor:
  interval: 5 #seconds
  resources: {}

uploader:
  parallelism: 8 # files uploaded at once
  resources: {}

ramdisk:
  # folders will be generated based on namespace
  # e.g. /dev/shm/colo-ch202/nmsg_partial, /dev/shm/colo-ch202/zst_partial, /dev/shm/colo-ch202/zst_complete
  # e.g. /dev/shm/colo-ch204/nmsg_partial, /dev/shm/colo-ch204/zst_partial, /dev/shm/colo-ch204/zst_complete
  srcPath: /dev/shm
  mountPath: /srv/ramdisk
  nmsgPartialDir: /srv/ramdisk/nmsg_partial
  zstPartialDir: /srv/ramdisk/zst_partial
  zstCompleteDir: /srv/ramdisk/zst_complete


replicaCount: 1

image:
  repository: infobloxcto/farsight-collector-colo
  tag: latest
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

nodeSelector: {}
